apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 6h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.12.x
  install:
    createNamespace: true
  interval: 6h0m0s
  targetNamespace: cert-manager
  upgrade:
    crds: Create
  values: {}
