---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: josmaredev_front
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: josmaredev_front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: josmaredev_front
    spec:
      containers:
        - name: josmaredev_front
          image: josmar/josmaredev:latest
          imagePullPolicy: Always
          resources: { }
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

