---
apiVersion: v1
kind: Service
metadata:
  name: josmaredev-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: josmaredev-front
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: josmare-front-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    cert-manager.io/cluster-issuer: letsencrypt-prod
#    kubernetes.io/tls-acme: "true"
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: josmare.fyi
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: josmaredev-svc
#                port:
#                  number: 80
#  tls:
#    - hosts:
#        - josmare.fyi
#      secretName: tls-nginx-general
