---
apiVersion: v1
kind: Service
metadata:
  name: josmaredev-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: josmaredev-front
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: josmare-front-ingress
#  annotations:
#    load-balancer.hetzner.cloud/name: "k8s-lb"
#    load-balancer.hetzner.cloud/location: "nbg1"
#    load-balancer.hetzner.cloud/use-private-ip: "true"
#    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
#    load-balancer.hetzner.cloud/hostname: "josmare.fyi"
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: josmare.fyi
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: josmaredev-svc
#                port:
#                  number: 80
#  tls:
#    - hosts:
#        - josmare.fyi
#      secretName: tls-nginx-general
