apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      interval: 6h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: '4.7.*' # v1.8.0 with 1.21.6
  install:
    createNamespace: true
  interval: 6h0m0s
  targetNamespace: ingress-nginx
