---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: josmaredev_front
  namespace: flux-system
spec:
  interval: 10m0s
  path: ../josmaredev_front
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
