---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-helm
      version: 2.0.x
  interval: 1m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$aoCu/XUElx3eZB6r47cxtO0.t5PJdhYKrHFFZl9DSjVeItNhHqbIy
      username: admin
    namespace: flux-system
    rbac:
      create: true
